In [1]:
import pandas as pd
from sympy.tensor import tensor
from tensorflow.python.framework.test_ops import type_list_restrict

In [3]:
import torch
print(torch.__version__)

2.14.0+cu130


In [7]:
if (torch.cuda.is_available()):
    print("CUDA available")
    print("Device name: ", torch.cuda.get_device_name(0))
    device = torch.device("cuda:0")
else:
    print("CUDA not available")
    device = torch.device("cpu")

CUDA available
Device name:  NVIDIA GeForce MX330


## creating an tensor

In [9]:
# Empty
torch.empty(2,3)

# When you call torch.empty(), PyTorch allocates a block of memory for a tensor of the specified shape, but it does not set or clear any values in that memory block. Whatever bits happen to be sitting in that allocated memory space at that moment will show up as your data, making the values completely unpredictable and arbitrary (often referred to as "garbage values")

tensor([[-1.6814e-06,  4.2064e-41, -1.6814e-06],
        [ 4.2064e-41,  0.0000e+00,  3.1746e-41]])

In [10]:
a = torch.empty(2,3)
print(type(a))

<class 'torch.Tensor'>


In [ ]:
torch.zeros(2,3)
torch.ones(2,3)
torch.rand(2,3)


In [13]:
# as we know that random function will generate a completely random numbers everytime we call them but if we want that everytime we get the same output again and again then we can use manual seeds that will return the same set of random numbers

torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [14]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [15]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [19]:
torch.linspace(0,10,5)

# linearly spaced --> means between 0 to 10, give me 5 evenly spaced values.

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [20]:
# for identity mtx or tensor
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [21]:
torch.full([2,3], 10)
# 2 X 3 mtx with each value filled as 10.



tensor([[10, 10, 10],
        [10, 10, 10]])

## checking the shape of tensor

In [22]:
a = torch.empty(2,3)
print("shape is, ", a.shape)

shape is,  torch.Size([2, 3])


In [23]:
# if we want to crate a tensor with the same shape as of a

torch.empty_like(a)

tensor([[-1.6814e-06,  4.2064e-41, -1.6814e-06],
        [ 4.2064e-41,  0.0000e+00,  0.0000e+00]])

In [24]:
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [28]:
torch.rand_like(a)  # this works only if a is of type float

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])

In [29]:
b = torch.tensor([[1,-2,3], [4,-5,6], [7,-8,9]], dtype=torch.float32) # here we have negative numbers as well

x = torch.abs(b) # this will convert the tensor a into its absolute value and we get every element as positive
x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [30]:
x = torch.neg(b) # this will convert the tensor a into its negative value
x

tensor([[-1.,  2., -3.],
        [-4.,  5., -6.],
        [-7.,  8., -9.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [31]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])


In [32]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [33]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [34]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [47]:
# clamp
torch.clamp(d, min=2, max=3)  # all values will be cliped between 2 and 3 any number less than 2 will be converted into 2 and any number greater than 3 will be converetd into 3

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction operation

In [36]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 0., 4.],
        [3., 8., 7.]])

In [37]:
# sum
torch.sum(e)

tensor(23.)

In [38]:
# sum along columns
torch.sum(e, dim=0)


tensor([ 4.,  8., 11.])

In [39]:
# sum along rows
torch.sum(e, dim=1)

tensor([ 5., 18.])

In [40]:
# mean
torch.mean(e)

tensor(3.8333)

In [41]:
# mean along col
torch.mean(e, dim=0)

tensor([2.0000, 4.0000, 5.5000])

In [42]:
# median
torch.median(e)
# max and min
torch.max(e)
torch.min(e)
# product
torch.prod(e)
# standard deviation
torch.std(e)
# variance
torch.var(e)
# argmax
torch.argmax(e)   # returns the position of maximum element in tensor
# argmin
torch.argmin(e)   # returns the position of minimum element in tensor

tensor(1)

## Matrix Operation

In [43]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[4, 6, 0],
        [1, 9, 9]])
tensor([[8, 0],
        [7, 0],
        [0, 9]])


In [44]:
# matrix multiplcation
torch.matmul(f, g)  # Matrix Multipliation

tensor([[74,  0],
        [71, 81]])

In [45]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [49]:
f = torch.randint(size=(2,3), low=0, high=10)
print(f)

tensor([[5, 7, 5],
        [9, 9, 7]])


In [53]:
# transpose
torch.transpose(f, 0,1)  # 0,1 means change rows with columns

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [55]:
f = torch.rand(3, 3)
torch.det(f)

tensor(-0.0192)

In [56]:
torch.inverse(f)

tensor([[-1.5502e+00,  6.0096e-01,  1.5547e+00],
        [ 2.0774e+00,  2.0056e+01, -2.6527e+01],
        [ 5.3806e-03, -1.1383e+01,  1.4940e+01]])

## Comparision operation

In [57]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [59]:
i > j  # comaprision between corresponding elements

tensor([[ True,  True, False],
        [ True, False, False]])

In [60]:
i < j

tensor([[False, False,  True],
        [False,  True,  True]])

In [ ]:
i == j
i != j
i >= j
i <= j

In [61]:
k = torch.randint(size=(2,3), low=0, high=10)
print(k)

tensor([[3, 3, 5],
        [0, 6, 4]])


In [62]:
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [63]:
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [64]:
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [65]:
torch.reciprocal(k)

tensor([[0.3333, 0.3333, 0.2000],
        [   inf, 0.1667, 0.2500]])

In [ ]:
torch.sigmoid(k)
torch.softmax(k)
torch.tanh(k)

# Check all other activation functions

## Inplace Operations

In [66]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [68]:
# if we want to add m and n tensor then it will allocate a whole new memort to result tensor like below
a = m + n
print(a)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])


In [71]:
# But if i wants to do this on place then add m and n and store the result either on place of m and n in the memory then

m.add_(n)  # add m and n and store the result on place of m

tensor([[1.6414, 0.4947, 1.9663],
        [1.6339, 0.5753, 2.5900]])

In [72]:
b = torch.relu(m)
print(b)  # relu will be performed on m and new memeory space is allocated to result

tensor([[1.6414, 0.4947, 1.9663],
        [1.6339, 0.5753, 2.5900]])


In [ ]:
m.relu_()  # relu is applied on the mtx m and result is stored on the place of m only instaed of creating an new memory space.


## Copying an tensor

In [73]:
a = torch.tensor([[1,2,3], [4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [74]:
# copy tensor a itno b
b = a

In [75]:
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [76]:
a[0][0] = 50

In [77]:
a

tensor([[50,  2,  3],
        [ 4,  5,  6]])

In [78]:
b

tensor([[50,  2,  3],
        [ 4,  5,  6]])

In [79]:
id(a)

128924806447328

In [80]:
id(b)

128924806447328

In [81]:
# Observe: chanegs made in original tesnor is reflected on copy as well
# to avoid this use clone
b = a.clone()

In [82]:
id(a)

128924806447328

In [83]:
id(b)  # now its on some other memory location

128924806449808

## Using GPU for code running

In [84]:
torch.cuda.is_available()

True

In [85]:
device = torch.device("cuda")

In [96]:
# creating new tensor on GPU
a = torch.tensor([[1,2,3], [4,5,6]], device=device)
a

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [87]:
b = torch.tensor([[1,2,3], [4,5,6]])
b

# this tensor is created on CPU

tensor([[1, 2, 3],
        [4, 5, 6]])

In [92]:
b.to(device)   # this will tranfer b on GPU from CPU

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [93]:
b + 5

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [97]:
a + 5

AcceleratorError: CUDA error: no kernel image is available for execution on the device
Search for `cudaErrorNoKernelImageForDevice' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.


In [100]:
c = torch.rand(226,226,3)
c.shape

torch.Size([226, 226, 3])

In [101]:
c.unsqueeze(0).shape  # here we are adding an new dimension at the 0th dimension

torch.Size([1, 226, 226, 3])

In [102]:
c.squeeze(0).shape

torch.Size([226, 226, 3])

In [ ]:
# read more about squeeze and unsqueeze operation